---
app_name: devops-app
# By default the image is dockerhub_username/app_name (username is in Vault)
docker_image_tag: latest
app_port: 5000
app_container_name: "{{ app_name }}"
app_restart_policy: unless-stopped
app_env: {}
health_endpoint: "/health"
health_timeout_seconds: 30
