replicaCount: 3
environment: prod
logLevel: WARN

image:
  repository: app_python-devops-info-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: http

statefulset:
  enabled: true
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate

rollout:
  enabled: false

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
  httpGet:
    path: /ready
    port: http

livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  httpGet:
    path: /health
    port: http

appConfig:
  serviceVersion: "1.0.0-prod-lab15"
  serviceDescription: "Production profile with StatefulSet and stable persistent identities"
