replicaCount: 3
environment: dev
logLevel: DEBUG

image:
  repository: app_python-devops-info-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: http

statefulset:
  enabled: true
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate

rollout:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

readinessProbe:
  initialDelaySeconds: 2
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
  httpGet:
    path: /ready
    port: http

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  httpGet:
    path: /health
    port: http

appConfig:
  serviceVersion: "1.0.0-dev-lab15"
  serviceDescription: "Development profile with StatefulSet and per-pod persistent storage"
