replicaCount: 5
environment: dev
logLevel: DEBUG

image:
  repository: app_python-devops-info-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: http

rollout:
  enabled: true
  strategy: canary
  canary:
    maxSurge: 1
    maxUnavailable: 0
    steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause:
          duration: 30s
      - setWeight: 60
      - pause:
          duration: 30s
      - setWeight: 80
      - pause:
          duration: 30s
      - setWeight: 100

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

readinessProbe:
  initialDelaySeconds: 2
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
  httpGet:
    path: /ready
    port: http

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  httpGet:
    path: /health
    port: http

appConfig:
  serviceVersion: "1.0.0-dev-lab14"
  serviceDescription: "Development profile with canary rollout managed by Argo Rollouts"
